version = 1

exclude_patterns = [
    "clients/spark/**",
    "design/**"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/treeverse/lakeFS"]

[[analyzers]]
name = "javascript"
enabled = true

